### PR TITLE
68 loading page

### PR DESCRIPTION
**Pull request by Georg-code**
Just a simple spinner, nothing fancy

### CODE REVIEW

**Review by b3h3m0th — APPROVED** [review]
cool!

**Comment by b3h3m0th** [comment]
What's the reason behind removing the `.module`? if it doesn’t have to be left out I would add it again.

**Comment by Georg-code** [comment]
> 
> 
> What's the reason behind removing the `.module`? if it doesn’t have to be left out I would add it again.

If you don't remove it, it doesn't load the scss for some reason. It's weird ik, but otherwise it does'nt work.

**Comment by b3h3m0th** [comment]
> > What's the reason behind removing the `.module`? if it doesn’t have to be left out I would add it again.
> 
> If you don't remove it, it doesn't load the scss for some reason. It's weird ik, but otherwise it does'nt work.

alright

**Pull request merged**
