### PR TITLE
73 Language System

### LINKED ISSUE #73: Language system frontend
Implement system for multiple website languages in frontend

### PR DESCRIPTION
**Pull request by b3h3m0th**
closes #73

This might be needed to resolve VSCode TS decorator errors: https://stackoverflow.com/a/62911130/12834972

### CODE REVIEW

**Comment by b3h3m0th** [comment]
Currently blocked by #75

**Comment by b3h3m0th** [comment]
resolved #75.

**Comment by b3h3m0th** [comment]
Please take a look at it and tell me if thats the way to go. Don't merge!

**Comment by b3h3m0th** [comment]
Nvm not completely done yet.

**Comment by b3h3m0th** [comment]
K im ready. Pls still do not merge!

**Review by Georg-code — COMMENTED** [review]
looks good

**Comment by b3h3m0th** [comment]
lets gooo. probably the best lines I have ever written

**Comment by b3h3m0th** [comment]
kannsch pls ufhöra remote branches einfach random zum löscha haha. wenn i ean num brucht hätt, hätt is scho seal to.

**Pull request merged**
