### PR TITLE
48 faq page

### PR DESCRIPTION
**Pull request by Georg-code**
FAQ Component for FAQ Page

### CODE REVIEW

**Comment by b3h3m0th** [comment]
Code's nice! accordean icon doesn't rotate? Is that how it's supposed to be?
And another thing: Don't you have an autoformatter? formatting is kinda werid.

**Review by b3h3m0th — COMMENTED** [review]
Code's nice! accordean icon doesn't rotate? Is that how it's supposed to be?
And another thing: Don't you have an autoformatter? formatting is kinda werid.

**Comment by Georg-code** [comment]
Weird.. on firefox it rotates.
Thanks for the review. I'll fix it

**Review by b3h3m0th — APPROVED** [review]
very nice!

**Pull request merged**
